2020-05-08 19:14:26,177 - D:/python/loging_test.py[line:39] - ERROR: error
2020-05-08 19:15:15,191 - D:/python/loging_test.py[line:39] - ERROR: error
2020-05-08 19:16:20,398 - D:/python/loging_test.py[line:39] - ERROR: error
2020-05-08 19:26:55,751 - D:/python/loging_test.py[line:39] - ERROR: error
2020-05-08 19:27:36,615 - D:/python/loging_test.py[line:39] - ERROR: error
